## CHANGE this to the name of your plugin.
name: SlimeVision

## CHANGE this to your username.
author: Bunnky

## CHANGE this to a meaninful but short description of your plugin.
description: Slime Vision is a Slimefun Addon that gives people a way to visualize their Slimefun machines with ease, and locate SF Block Storage data.

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.bunnky.slimevision.SlimeVision

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Bunnky/SlimeVision

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.20

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun

softdepend:
- Networks