name: SlimeVision
author: Bunnky
description: Slime Vision is a Slimefun Addon that gives people a way to visualize their Slimefun machines with ease, and locate SF Block Storage data.
main: me.bunnky.slimevision.SlimeVision
website: https://github.com/Bunnky/SlimeVision
version: ${project.version}
api-version: 1.20
depend:
- Slimefun
softdepend:
- Networks