name: Blob Build Deployment

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Upload Release
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[ci skip]') == false
    steps:
      - uses: actions/checkout@v4
      - name: Setup java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload to Blob Builds
        uses: WalshyDev/blob-builds/gh-action@main
        with:
          project: SlimeVision
          apiToken: ${{ secrets.BLOB_BUILDS_API_TOKEN }}
          file: ./target/SlimeVision.jar
          releaseNotes: ${{ github.event.head_commit.message }}
          releaseChannel: 'Dev'